apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-16T09:17:09Z"
  generation: 1
  labels:
    app: mlops-pipeline-imdb-339a41a
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"mlops-pipeline-imdb-1"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"BIGQUERY_RAW_DATASET"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"BIGQUERY_RAW_TABLE_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"GCS_BUCKET_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"GCS_BUCKET_PROJECT_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"GOOGLE_APPLICATION_CREDENTIALS"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                  k:{"name":"PROJECT_ID"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2023-06-16T09:17:09Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2023-06-16T09:43:58Z"
  name: mlops-pipeline-imdb-339a41a
  namespace: default
  resourceVersion: "15901"
  uid: a6d893c3-eb9f-4203-9491-333b2f98aedf
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mlops-pipeline-imdb-339a41a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mlops-pipeline-imdb-339a41a
    spec:
      containers:
      - env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: PROJECT_ID
              name: mlops-pipeline-imdb-339a41a-config-vstv
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_APPLICATION_CREDENTIALS
              name: mlops-pipeline-imdb-339a41a-config-vstv
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              key: GCS_BUCKET_NAME
              name: mlops-pipeline-imdb-339a41a-config-vstv
        - name: GCS_BUCKET_PROJECT_NAME
          valueFrom:
            configMapKeyRef:
              key: GCS_BUCKET_PROJECT_NAME
              name: mlops-pipeline-imdb-339a41a-config-vstv
        - name: BIGQUERY_RAW_DATASET
          valueFrom:
            configMapKeyRef:
              key: BIGQUERY_RAW_DATASET
              name: mlops-pipeline-imdb-339a41a-config-vstv
        - name: BIGQUERY_RAW_TABLE_NAME
          valueFrom:
            configMapKeyRef:
              key: BIGQUERY_RAW_TABLE_NAME
              name: mlops-pipeline-imdb-339a41a-config-vstv
        image: us-west2-docker.pkg.dev/gao-hongnan/imdb-repo/mlops-pipeline-imdb:339a41a
        imagePullPolicy: IfNotPresent
        name: mlops-pipeline-imdb-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-06-16T09:17:09Z"
    lastUpdateTime: "2023-06-16T09:17:09Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-06-16T09:43:57Z"
    lastUpdateTime: "2023-06-16T09:43:57Z"
    message: ReplicaSet "mlops-pipeline-imdb-339a41a-b4f5848d9" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
